/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._ivc_proyectoga4_josemontenegro;

import javax.swing.JOptionPane;

/**
 *
 * @author H4H7X
 */
public class jfrmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmMenu.class.getName());

    /**
     * Creates new form jfrmMenu
     */
    public jfrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnBoton1 = new javax.swing.JButton();
        jbtnBoton2 = new javax.swing.JButton();
        jbtnBoton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Menú Principal");

        jbtnBoton1.setText("Botón 1");
        jbtnBoton1.addActionListener(this::jbtnBoton1ActionPerformed);

        jbtnBoton2.setText("Botón 2");
        jbtnBoton2.addActionListener(this::jbtnBoton2ActionPerformed);

        jbtnBoton3.setText("Botón 3");
        jbtnBoton3.addActionListener(this::jbtnBoton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbtnBoton1)
                .addGap(48, 48, 48)
                .addComponent(jbtnBoton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jbtnBoton3)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBoton1)
                    .addComponent(jbtnBoton3)
                    .addComponent(jbtnBoton2))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoton1ActionPerformed
        // TODO add your handling code here:
        jfrmConver v1=new jfrmConver();
        v1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jbtnBoton1ActionPerformed

    private void jbtnBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoton2ActionPerformed
        // TODO add your handling code here:
        jfrmEje2 v2=new jfrmEje2();
        v2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jbtnBoton2ActionPerformed

    private void jbtnBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoton3ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea Salir del Sistema?",
                "Colegio Don Bosco",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jbtnBoton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnBoton1;
    private javax.swing.JButton jbtnBoton2;
    private javax.swing.JButton jbtnBoton3;
    // End of variables declaration//GEN-END:variables
}
